#!name=小红书
#!desc=小红书去广告.图片水印
[Rule]
AND,((PROTOCOL,UDP),(DST-PORT,443),(DOMAIN-SUFFIX,xiaohongshu.com)),REJECT


[URL Rewrite]
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/surprisebox\/(?:get_style|open|submit_action) - reject-dict
^https:\/\/www\.xiaohongshu\.com\/api\/marketing\/box\/trigger\? - reject-dict
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v2\/guide\/user_banner|v3\/note\/guide) - reject-dict
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/(?:v1\/ads\/resource|v2\/hey\/\w+\/hey_gallery) - reject-dict


[Script]

# 视频流
小红书视频 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v3\/note\/videofeed\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 视频详情
小红书详情 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/note\/feed\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 图片流
小红书图片 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/note\/(imagefeed|live_photo\/save),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 首页推荐
小红书首页 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v6\/homefeed\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 关注流
小红书关注 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v4\/followfeed\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 搜索
小红书搜索 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v10\/search\/notes\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 搜索提示
小红书提示 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v4\/search\/(hint|trending)\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 开屏配置
小红书开屏 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/system_service\/splash_config,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60

# 系统配置
小红书配置 = type=http-response,pattern=^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/system_service\/config\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QDwbd/srule/main/egern/xhs.js,timeout=60


[MITM]
hostname = %APPEND% edith.xiaohongshu.com,www.xiaohongshu.com
