export default async function(ctx){
const C={
bg:{light:'#FFFFFF',dark:'#050506'},
text:{light:'#111114',dark:'#F7F7F8'},
dim:{light:'#7B7B84',dark:'#85858E'},
panel:{light:'#F5F5F7',dark:'#111114'},
line:{light:'#E4E4E8',dark:'#242429'},
accent:{light:'#7446D8',dark:'#B765FF'},
ok:{light:'#2F9E58',dark:'#C7FF18'}
};
const isSmall=ctx.widgetFamily==='systemSmall';
const isMedium=ctx.widgetFamily==='systemMedium';
async function fetchRate(){
try{
const res=await ctx.http.get(
'https://api.frankfurter.app/latest?from=USD&to=CNY,EUR,JPY,GBP,HKD,KRW,AUD,CAD,SGD,TRY',
{timeout:5000}
);
const data=JSON.parse(await res.text());
return{
ok:true,
rates:{USD:1,...data.rates}
};
}catch{
return{ok:false};
}
}
const rate=await fetchRate();
const now=new Date();
const time=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;
if(isSmall){
return{
type:'widget',
backgroundColor:C.bg,
padding:12,
children:[
{
type:'stack',
direction:'column',
alignItems:'center',
justifyContent:'center',
gap:5,
children:[
{
type:'text',
text:'1 USD',
font:{
size:13,
weight:'bold',
design:'monospaced'
},
textColor:C.dim
},
{
type:'text',
text:'↓',
font:{
size:18,
weight:'bold'
},
textColor:C.accent
},
{
type:'text',
text:rate.ok?rate.rates.CNY.toFixed(4):'--',
font:{
size:32,
weight:'bold',
design:'monospaced'
},
textColor:C.text
},
{
type:'text',
text:'人民币',
font:{
size:12,
weight:'medium'
},
textColor:C.dim
}
]
}
]
};
}
let currencies=[
{flag:'🇪🇺',name:'EUR',title:'欧元'},
{flag:'🇯🇵',name:'JPY',title:'日元'},
{flag:'🇬🇧',name:'GBP',title:'英镑'},
{flag:'🇭🇰',name:'HKD',title:'港币'},
{flag:'🇰🇷',name:'KRW',title:'韩元'},
{flag:'🇦🇺',name:'AUD',title:'澳元'},
{flag:'🇨🇦',name:'CAD',title:'加元'},
{flag:'🇸🇬',name:'SGD',title:'新加坡元'},
{flag:'🇹🇷',name:'TRY',title:'土耳其里拉'}
];
if(isMedium){
currencies=currencies.slice(0,6);
}
const RateTable=()=>{
const rows=[];
rows.push({
type:'stack',
direction:'row',
children:[
{
type:'text',
text:'货币',
font:{
size:isMedium?9:11,
weight:'bold'
},
textColor:C.accent,
flex:1
},
{
type:'text',
text:'USD',
font:{
size:isMedium?9:11,
weight:'bold',
design:'monospaced'
},
textColor:C.accent,
flex:1,
textAlignment:'right'
},
{
type:'text',
text:'CNY',
font:{
size:isMedium?9:11,
weight:'bold',
design:'monospaced'
},
textColor:C.accent,
flex:1,
textAlignment:'right'
}
]
});
currencies.forEach((item,index)=>{
const usd=rate.ok?rate.rates[item.name]:0;
const cny=rate.ok?rate.rates[item.name]/rate.rates.CNY:0;
rows.push({
type:'stack',
direction:'row',
alignItems:'center',
children:[
{
type:'text',
text:`${item.flag} ${item.title}`,
font:{
size:isMedium?10:13,
weight:'medium'
},
textColor:C.text,
flex:1
},
{
type:'text',
text:rate.ok?usd.toFixed(item.name==='JPY'||item.name==='KRW'?2:4):'--',
font:{
size:isMedium?10:12,
design:'monospaced'
},
textColor:C.text,
flex:1,
textAlignment:'right'
},
{
type:'text',
text:rate.ok?cny.toFixed(item.name==='JPY'||item.name==='KRW'?2:4):'--',
font:{
size:isMedium?10:12,
design:'monospaced'
},
textColor:C.dim,
flex:1,
textAlignment:'right'
}
]
});
if(index!==currencies.length-1){
rows.push({
type:'stack',
height:1,
backgroundColor:C.line
});
}
});
return{
type:'stack',
direction:'column',
gap:isMedium?4:7,
padding:isMedium?[8,10]:[12,14],
backgroundColor:C.panel,
borderRadius:10,
children:rows
};
};
if(isMedium){
return{
type:'widget',
backgroundColor:C.bg,
padding:[10,12],
gap:8,
children:[
{
type:'stack',
direction:'row',
alignItems:'center',
children:[
{
type:'image',
src:'sf-symbol:banknote',
color:C.ok,
width:12,
height:12
},
{
type:'text',
text:'汇率转换',
font:{
size:12,
weight:'bold'
},
textColor:C.text
},
{
type:'spacer'
},
{
type:'text',
text:time,
font:{
size:10,
design:'monospaced'
},
textColor:C.dim
}
]
},
{
type:'text',
text:rate.ok?`1 USD = ${rate.rates.CNY.toFixed(4)} CNY`:'OFFLINE',
font:{
size:15,
weight:'bold',
design:'monospaced'
},
textColor:C.text
},
RateTable()
]
};
}
return{
type:'widget',
backgroundColor:C.bg,
padding:[14,16],
gap:10,
children:[
{
type:'stack',
direction:'row',
children:[
{
type:'text',
text:'汇率转换',
font:{
size:11,
weight:'bold'
},
textColor:C.dim
},
{
type:'spacer'
},
{
type:'text',
text:time,
font:{
size:11,
design:'monospaced'
},
textColor:C.dim
}
]
},
{
type:'text',
text:rate.ok?`1 USD = ${rate.rates.CNY.toFixed(4)} CNY`:'RATE ERROR',
font:{
size:25,
weight:'bold',
design:'monospaced'
},
textColor:C.text
},
{
type:'text',
text:'USD / CNY GLOBAL RATE',
font:{
size:11
},
textColor:C.dim
},
RateTable()
]
};
}
